import React, { FC } from 'react'
import Head from 'next/head'
import { signIn } from 'next-auth/react'
import PageWithLayoutType from '../../types/pageWithLayoutType';
import DefaultLayout from '../../components/layouts/Default';

const Login: FC = () => {
  const handleSignIn = async () => {
    await signIn('github', {
      callbackUrl: 'http://localhost:3000/dashboard'
    })
  }

  return (
    <div className="main-container">
      <Head>
        <title>Next Blog Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Login</h1>
      <div>
        <button onClick={handleSignIn}>github login</button>
      </div>
    </div>
  )
}

(Login as PageWithLayoutType).layout = DefaultLayout

export default Login