import React, { FC } from 'react'
import Head from 'next/head'
import PageWithLayoutType from '../../types/pageWithLayoutType';
import DefaultLayout from '../../components/layouts/Default';

const About: FC = () => {
  return (
    <div>
      <Head>
        <title>Next Blog About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     <h1>About</h1>
     <p>The Next.js router allows you to do client-side route transitions between pages, similar to a single-page application.</p>
    </div>
  )
}

(About as PageWithLayoutType).layout = DefaultLayout

export default About